name: docu

on: 
  push:
  pull_request: 
    paths:
      - 'src/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 30
    steps:
      # - uses: actions/checkout@v2
      # #
      # - name: Fetch unshallow
        # run: git fetch --unshallow
      #
      - name: Clean folder
        run: |
          rm -r -force
      #
      - name: Checkout main repo
        uses: actions/checkout@v2
        with:
          repository: jozefchmelar/TcOpen-1
          path: TcOpen
      
      - name: Checkout docu repo
        uses: actions/checkout@v2
        with:
          repository: TcOpenGroup/TcOpen.Documentation
          path: TcOpen.Documentation
      
      - name : Build TcOpen
        run: |
            cd TcOpen
            git fetch --unshallow
            .\pipelines\runbuild.ps1 -properties @{"buildConfig" = "Release";  "updateAssemblyInfo" = $true}
            cd ..

      - name : Build TcOpen.Documentation
        run: |
            cd TcOpen.Documentation
            dotnet build
            git add -A
            git commit -m "Updated documentation"
#git push

